spring:

  application:
    name: wixblog

  datasource:
    url: jdbc:postgresql://localhost:5432/wixblog
    username: wixblog
    password: 123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

    open-in-view: false

    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: "classpath:certs/public2-key.pem"
          private-key-location: "classpath:certs/private2_pkcs8.pem"
          issuer: wixblog-api
          access-token-expiration-seconds: 1800

  flyway:
    enabled: true
    locations: classpath:db/migration



server:
  port: 8080